"use client";

import Link from "next/link";
import { useApp } from "@/lib/store";
import { MATRIX_GAME_MODES, MATRIX_MODE_DETAILS } from "@/lib/matrix/game-modes";
import { Button3D, Card, Pill } from "@/components/matrix/ui";

export function MatrixGameModes() {
  const entries = useApp((state) => state.entries);
  const weekend = [0, 6].includes(new Date().getDay());
  return <div className="mx-auto max-w-4xl space-y-5 pb-10"><header><nav className="text-xs text-muted"><Link href="/practice" className="hover:text-ink hover:underline">Practise</Link> / <Link href="/practice/matrix" className="hover:text-ink hover:underline">Matrix</Link> / <span className="text-ink">Game modes</span></nav><h1 className="mt-2 text-2xl font-semibold text-ink">Game modes</h1><p className="mt-1 text-sm text-muted">Choose a recorded trade, then choose how to train it.</p></header><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{MATRIX_GAME_MODES.map((mode) => <Card key={mode} className="flex min-h-40 flex-col"><h2 className="text-sm font-semibold text-ink">{MATRIX_MODE_DETAILS[mode].label}</h2><p className="mt-2 flex-1 text-xs leading-relaxed text-muted">{MATRIX_MODE_DETAILS[mode].description}</p><Pill tone={mode === "time-attack" ? "green" : "muted"}>{mode === "time-attack" ? "1.5× XP" : "Recorded evidence only"}</Pill></Card>)}</section><Card className="flex flex-wrap items-center justify-between gap-4 border-loss/35"><div><h2 className="text-sm font-semibold text-ink">Weekend Boss</h2><p className="mt-1 text-xs text-muted">{weekend ? "Active now: a fresh multi-trade run every time." : "Available Saturday and Sunday only."}</p></div>{weekend ? <Link href="/practice/matrix/weekend-boss"><Button3D>Play Boss →</Button3D></Link> : <Pill tone="muted">Returns Saturday</Pill>}</Card><section><h2 className="text-sm font-semibold text-ink">Choose a trade</h2><Card className="mt-3 overflow-hidden p-0">{entries.length ? entries.map((entry) => <div key={entry.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-line px-4 py-3 last:border-b-0"><div><p className="text-sm font-medium text-ink">{entry.instrument} · {entry.date}</p><p className="mt-1 text-xs text-muted">{entry.setup || "No recorded setup"}</p></div><div className="flex flex-wrap gap-2">{MATRIX_GAME_MODES.map((mode) => { const calculation = mode === "what-if" || mode === "pro"; const ready = !calculation || (entry.entryPrice != null && entry.stopLoss != null && entry.direction != null && entry.entryPrice !== entry.stopLoss); return ready ? <Link key={mode} href={`/practice/matrix/${entry.id}/test?mode=${mode}`}><Button3D tone={mode === "classic" ? "primary" : "secondary"}>{MATRIX_MODE_DETAILS[mode].label}</Button3D></Link> : <Pill key={mode} tone="muted">{MATRIX_MODE_DETAILS[mode].label}: needs prices</Pill>; })}</div></div>) : <p className="p-6 text-center text-sm text-muted">Record a trade first; Matrix never creates one for you.</p>}</Card></section><Card><h2 className="text-sm font-semibold text-ink">Leaderboard</h2><p className="mt-2 text-xs text-muted">Coming soon. There is no Matrix friends or ranking backend to display yet.</p><Pill tone="muted">Coming soon</Pill></Card></div>;
}
