"use client";

import { useState } from "react";
import { AccuracyRing, Badge, Breadcrumb, Button3D, Card, GameTile, OptionRow, Pill, ProgressBar, StarRating } from "@/components/matrix/ui";

export default function MatrixUiPreviewPage() {
  const [option, setOption] = useState<"default" | "selected" | "correct" | "wrong">("selected");
  return <div className="mx-auto max-w-5xl space-y-8 pb-12"><header><p className="text-xs font-semibold tracking-wide text-gold">Matrix · development preview</p><h1 className="mt-1 text-2xl font-semibold text-ink">Shared UI kit</h1><p className="mt-2 text-sm text-muted">Visual states only. No trade data is used on this route.</p></header><Card><Breadcrumb items={[{ label: "Practise" }, { label: "Matrix" }, { label: "UI kit" }]} /><div className="mt-4 flex flex-wrap gap-2"><Button3D>Primary gold</Button3D><Button3D tone="secondary">Secondary outline</Button3D><Button3D disabled>Disabled</Button3D><Pill>+10 XP</Pill><Pill tone="green">+2 tokens</Pill><Pill tone="muted">Due tomorrow</Pill></div></Card><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><GameTile title="Practise" detail="Math and revision drills" tone="green" /><GameTile title="Matrix" detail="Your recorded trade tests" tone="purple" /><GameTile title="Daily challenge" detail="Earn XP and tokens" tone="gold" /><GameTile title="Weekend Boss" detail="Harder scenarios" tone="red" /></section><section className="grid gap-4 lg:grid-cols-2"><Card><h2 className="text-sm font-semibold text-ink">Answer states</h2><div className="mt-3 space-y-2"><OptionRow prefix="A" label="Default option" state="default" onClick={() => setOption("default")} /><OptionRow prefix="B" label="Selected option" state={option === "selected" ? "selected" : "default"} onClick={() => setOption("selected")} /><OptionRow prefix="C" label="Correct answer" state="correct" /><OptionRow prefix="D" label="Wrong answer" state="wrong" /></div></Card><Card><h2 className="text-sm font-semibold text-ink">Progress and ratings</h2><div className="mt-4 grid grid-cols-[auto_1fr] items-center gap-5"><AccuracyRing value={80} /><div className="space-y-4"><ProgressBar value={42} label="Today’s progress" /><div><p className="mb-1 text-xs text-muted">Trade mastery</p><StarRating value={2} /></div></div></div></Card></section><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Badge title="First win" earned detail="Complete one Matrix" /><Badge title="Three-day streak" earned detail="Practise three days" /><Badge title="Matrix master" detail="100 correct" /><Badge title="Weekend Boss" detail="Complete one boss" /></section></div>;
}
